version: "3.8"
services:


  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: fastfood-payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fastfood
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

    #  mongo:
    #    image: mongo:latest
    #    container_name: mongo
    #    restart: always
    #    environment:
    #      MONGO_INITDB_DATABASE: fastfood-payment
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: example
    #    ports:
    #      - "27018:27017"
    #    networks:
    #      - fastfood
    #    healthcheck:
    #      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
    #      interval: 10s
    #      timeout: 5s
    #      retries: 5

    #Configuração do Prometheus


  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs, sns
      DEBUG: "1"
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SESSION_TOKEN: test
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./local/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"

volumes:
  pgdata:

networks:
  fastfood:
