version: "3.8"
services:
  # Configuração da app
  #  app:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: app
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - db
  #    environment:
  #      SPRING_PROFILES_ACTIVE: dev
  #      DB_URL: jdbc:postgresql://db:5432/fastfood
  #      DB_USER: postgres
  #      DB_PASS: postgres
  #    restart: always
  #    networks:
  #      - fastfood
  #    healthcheck:
  #      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health || exit 1" ]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 5

  # Configuração do PostgreSQL
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ms-payment
      MONGO_INITDB_ROOT_PASSWORD: password
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: fastfood-payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - fastfood
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Configuração do Promet heus
#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./local/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#      - fastfood
#    depends_on:
#      - app
#    healthcheck:
#      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9090/-/ready" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  # Configuração do Grafana
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - "3001:3000"
#    networks:
#      - fastfood
#    depends_on:
#      - prometheus
#    volumes:
#      - grafana-storage:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    healthcheck:
#      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000/login" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

#  # Configuração do Loki
#  loki:
#    image: grafana/loki:2.9.2
#    container_name: loki
#    ports:
#      - "3100:3100"
#    command: -config.file=/etc/loki/loki-config.yml
#    volumes:
#      - ./local/loki/loki-config.yml:/etc/loki/loki-config.yml
#      - loki-data:/loki
#    networks:
#      - fastfood
#    healthcheck:
#      test: [ "CMD-SHELL", "wget --spider -q http://localhost:3100/ready || exit 1" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  # Configuração do Promtail
#  promtail:
#    image: grafana/promtail:2.9.2
#    container_name: promtail
#    command: -config.file=/etc/promtail/promtail-config.yml
#    volumes:
#      - ./local/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
#      - /var/log:/var/log
#      - /var/lib/docker/containers:/var/lib/docker/containers:ro
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - fastfood
#    depends_on:
#      - loki

volumes:
  pgdata:
#  grafana-storage:
#  loki-data:

networks:
  fastfood:
