spring:
  application:
    name: ms-payment-fastfood
  profiles:
    default: dev
    active: dev
  jpa:
    generate-ddl: false
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  swagger-ui:
    enabled: true

api:
  security:
    token:
      secret: ${JWT_SECRET:minha-secret}

mercadoPago:
  publicKey: ${PUBLIC_KEY:public-key}
  accessToken: ${ACCESS_TOKEN:access-token}
  clientId: ${CLIENT_ID:client-id}
  clientSecret: ${CLIENT_SECRET:client-secret}
  externalPosID: ${EXTERNAL_POS_ID:external-pos-id}
  webhook:
    secretKey: ${WEBHOOK_SECRET:webhook-secret}