spring:
  config:
    activate:
      on-profile: dev
  # Configurações do banco de dados PostgreSQL
  flyway:
    enabled: false

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/fastfood-payment}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    # Configurações do MongoDB
  mongodb:
    uri: mongodb://root:example@localhost:27018/fastfood-payment?authSource=admin

  security:
    token:
      secret: ${JWT_SECRET:minha-secret}

