spring:
  application:
    name: ms-payment-fastfood
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none # Security best practice: handle via Flyway

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    enabled: true

server:
  port: ${SERVER_PORT:8084}

# Shared Mercado Pago Config
mercadoPago:
  publicKey: ${PUBLIC_KEY}
  accessToken: ${ACCESS_TOKEN}
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  externalPosID: ${EXTERNAL_POS_ID}
  webhook:
    secretKey: ${WEBHOOK_SECRET}

cloud:
  aws:
    region:
      static: ${AWS_REGION:us-east-1}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}