---
name: Create PR to Main

on:
  push:
    branches:
      - stage

jobs:
  create-pr-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar Pull Request para Main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: stage
          title: 'Merge stage into main'
          body: |
            PR automática da branch `stage` para `main`.
          labels: automatic-pr
          commit-message: '[create-pull-request] chore: create PR'
          signoff: true
          author: >
            ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          delete-branch: false
          always-create: true
          branch-suffix: timestamp
